---
title: "R Notebook"
output: 
  html_document: 
    df_print: default
editor_options: 
  chunk_output_type: console
author: "Nick Wang"
---

```{r setup}
library(tidyverse)
library(tidytext)
library(KoNLP)
library(wordcloud)
stop_pos09 <- stopwords::stopwords(language="ko", source = "stopwords-iso") %>%
  SimplePos09() %>%
  unlist() %>%
  str_extract("\\p{Hangul}+") %>%
  unique()
```

```{r import}
raw_pdf <- pdftools::pdf_text("/micehome/nwang/repos/datastory/misc/어린 왕자.pdf")

tlp <- raw_pdf %>%
  str_flatten() %>%
  str_split("      [\\d\\d|\\d]") %>%
  unlist() %>%
  .[-1] %>%
  str_replace_all("[a-zA-Z\\n]", "") %>%
  str_replace_all("^\\.", "") %>%
  str_trim(side="both")
```

```{r tokenize, dependson=import, cache=TRUE}
tokens <- tlp %>%
  paste0("Chapter", seq(length(.)), ., collapse="") %>%
  str_replace_all("“|”", "") %>%
  str_replace_all("\\.|\\?|!", "\\.Sentence_End") %>%
  str_split("Sentence_End") %>%
  unlist() %>%
  str_trim() %>%
  tibble(text=.) %>%
  mutate(
    chapter=cumsum(str_detect(text,"Chapter\\d")),
    sentence=row_number(),
    text=str_replace_all(text, "Chapter\\d", ""),
    pos09 = SimplePos09(text),
    word = map(pos09, function(pos09) {pos09 %>% names()})
         ) %>%
  unnest(pos09, word) %>%
  mutate(pos09 = str_split(pos09, "\\+")) %>%
  unnest(pos09) %>%
  mutate(tag = case_when(
    str_detect(pos09, "/N") ~ "nominal",
    str_detect(pos09, "/P") ~ "predicate",
    str_detect(pos09, "/M") ~ "modifier",
    str_detect(pos09, "/I") ~ "interjection",
    str_detect(pos09, "/J") ~ "relational suffix",
    str_detect(pos09, "/E") ~ "ending",
    str_detect(pos09, "/X") ~ "affix",
    str_detect(pos09, "/S") ~ "symbol",
    str_detect(pos09, "/F") ~ "foreign word"
  ),
  pos09 = str_replace(pos09, "/[NPMIJEXSF]", "")
  )
```

```{r tagwise_freq}
# some pos09 like 는 appear in more than one tag, so it counts only one of them for the reordering... how to fix this?
tokens %>%
  group_by(tag,pos09) %>%
  summarise(count=n()) %>%
  arrange(desc(count)) %>%
  top_n(5) %>%
  ungroup() %>%
  mutate(pos09 = reorder(pos09, count)) %>%
  ggplot(aes(pos09, count)) +
  geom_col(aes(fill=tag), show.legend=FALSE) +
  xlab(NULL) +
  ylab(NULL) +
  coord_flip() +
  facet_wrap(~tag, scale="free")
```

```{r wordcloud}
png("/home/nwang/repos/datastory/misc/temp.png", width=1000, height=1000, res=250)
tokens %>%
  filter(!(tag %in% c("relational suffix","ending","symbol"))) %>%
  filter(!(pos09 %in% stop_pos09)) %>%
  count(pos09, sort=TRUE) %>%
  # filter(n<=mean(n)+3*sd(n)) %>%
    with(wordcloud(pos09, n,
                   scale=c(4,0.25),
                   max.words=Inf,
                   colors=rainbow(50),
                   random.order=FALSE,
                   rot.per=0))
dev.off()
```

