---
title: "Estimator Consistency"
author: "Nick Wang"
date: "February 27, 2019"
output: 
  html_document: 
    df_print: default
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
library(tidyverse)
```

```{r df}
N <- 5000
df <- crossing(
  sequence=seq(10) %>% as.character(),
  p=seq(0.15,0.9,0.15),
  n=seq(N)
) %>%
  group_by(sequence, p) %>%
  mutate(X=rbinom(n=N,size=1,prob=p),
         cumsum = cumsum(X),
         p_n=cumsum/n)
```

```{r vis}
df %>%
  ggplot() +
  geom_line(aes(x=n,y=p_n, colour=sequence)) +
  ylim(0,1) +
  facet_wrap(~p)
```

The variance of the estimated $\hat{p_n}$ decreases when the trials increases.
```{r point_estimation}
p <- 0.5
crossing(
  trials = c(50, 100, 200, 400, 800, 1600),
  sequence = seq(1000) %>% as.character()
) %>%
  group_by(sequence, trials) %>%
  mutate(sum_success = rbinom(n=trials, size=1, prob=p) %>% sum(),
         p_n =sum_success/trials) %>%
  ggplot() + 
  geom_histogram(aes(x=p_n), breaks=seq(0.25,0.75,0.01)) +
  facet_wrap(~trials)
```

